# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-fastapi
  template:
    metadata:
      labels:
        app: rag-fastapi
    spec:
      containers:
      - name: rag-fastapi-app
        image: saishashank11/rag-fastapi-app:latest
        ports:
        - containerPort: 8000