# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rag-fastapi-service
spec:
  selector:
    app: rag-fastapi
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000